### ISSUE TITLE
pin siggen version and surface it somehow

### ISSUE THREAD

**Issue by willkg** [Ben-Wu/fx-crash-sig#4]
siggen will likely get an update any time we make changes in Socorro to signature generation. Because of that, it's likely it'll have lots of updates and using an older version of siggen can result in bad signatures that don't match what Socorro is generating.

siggen is using semantic versioning, so we should adjust fx-crash-sig to install siggen for the current API-compatible series.

Further, fx-crash-sig should make it clear which version of siggen is being used somehow. I don't know if it has output or maybe we add a method that prints the version of fx-crash-sig and the version of siggen or something like that.

**Comment by willkg** [comment]
I just pushed out a 1.0.0, so we can restrict the siggen installed to `<2`.

**Comment by Ben-Wu** [comment]
Closed with #5
